### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by quasicomputational** [simonmar/ghc-paths#18]
Hi - the change from #13 will be strictly needed when Cabal 3.0 and GHC 8.8 become things. Currently, it's in no released version. It's not pressing at the moment, but at some point in the near future a release would be quite handy, please.

**Comment by quasicomputational** [comment]
Cabal 3.0 has been released. Once bounds are relaxed (e.g., by merging #17 or #19), a release would be helpful.

**Comment by simonmar** [comment]
http://hackage.haskell.org/package/ghc-paths-0.1.0.12
